 # In this notebook, we are going to cover some of the most fundamental concepts
 # tensors using tensorflow

More specifically , we are going to cover :
    1.introduction to tensors
    2.Getting information from tnesors
    3.Manipulating tensors
    4.Tensors and Numpy
    5.using @tf.function(a way to speed up your regular python functions)
    6. using GPUs with TensorFlow(or TPU)
    7. Exercises to try yourself

In [1]:
#Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.10.0


In [2]:
# Create tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check the number of dimension of the tensor
scalar.ndim

0

In [4]:
# create a vector
vector=tf.constant([10,20])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20])>

In [5]:
# check the dimension of our vector
vector.ndim

1

In [6]:
# create a matrix(having more than 1 dimension)
matrix=tf.constant([[10,7],
                   [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [7]:
matrix.ndim

2

In [8]:
# create another matrix
another_matrix=tf.constant([[10.,7.],
                           [3.,2.],
                           [8.,9.]], dtype=tf.float16) #specifying the data type
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
# Let's create another tensor
tensor=tf.constant([[[1,2,3,4],
                    [5,6,7,8]],
                   [[9,10,11,12],
                   [13,14,15,16]],
                   [[17,18,19,20],
                   [21,22,23,24]]])
tensor

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [11]:
tensor.ndim

3

what we have created so far
* scalar:a single number
* Vector:a number with direction(e.g wind speed and direction)
* Matrix:a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers(where "n" can be any number , a 0-dimensional tensor is a scalar, a1-dimensional tensor is a vector)


 # Creating tensor with tf.Variable

In [12]:
changable_tensor=tf.Variable([10,7])
unchangable_tensor=tf.constant([7,10])
changable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>)

In [13]:
changable_tensor[0]=7
changable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [14]:
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [15]:
unchangable_tensor[0].assign(7)
unchangable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

* We can say that tensor created with Varable are changable 
* while the tensor created with constant are not changable 

# Creating Random tensor

Random tensors are tensors of some  arbitary size which contain random numbers

In [16]:
# Create two random(but the same ) tensors
random_1=tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

* Shuffle the order of elements in tensors

In [17]:
#Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order does not effect the learning)
not_shuffled=tf.constant([[2,3],[6,7],[4,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [6, 7],
       [4, 5]])>

In [18]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5],
       [6, 7]])>

In [21]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [6, 7],
       [4, 5]])>

In [22]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=32)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [2, 3],
       [6, 7]])>

In [23]:
tf.random.shuffle(not_shuffled,seed=32)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [6, 7],
       [2, 3]])>

In [24]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[6, 7],
       [4, 5],
       [2, 3]])>

* Another way of creating tensor 

In [25]:
tf.ones(shape=[5,4],dtype=tf.float16)

<tf.Tensor: shape=(5, 4), dtype=float16, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float16)>

In [26]:
tf.zeros(shape=[4,4],dtype=tf.int32)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])>

*Creating Tensors from numpy array

In [27]:
#importing numpy
import numpy as np

In [28]:
numpy_A=np.arange(1,25,dtype=int)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [29]:
A=tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [30]:
tf.constant(numpy_A,shape=(2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [31]:
tf.constant(numpy_A,shape=(3,8))

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])>

#Getting information out of the Tensors
* Shape 
* Size 
* Rank 
* Dimension

In [35]:
teen=tf.ones(shape=(2,3,2,5),dtype=tf.int32)
teen

<tf.Tensor: shape=(2, 3, 2, 5), dtype=int32, numpy=
array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]]])>

In [38]:
print('Number of elements in tensor',tf.size(teen).numpy())
print('Shape of the tensor',teen.shape)
print('Dimension of the tensor',teen.ndim)
print('Datatype of the all elements in the tensor',teen.dtype)
print('Element along 0-axis',teen.shape[0])
print('Element along last axis',teen.shape[-1])

Number of elements in tensor 60
Shape of the tensor (2, 3, 2, 5)
Dimension of the tensor 4
Datatype of the all elements in the tensor <dtype: 'int32'>
Element along 0-axis 2
Element along last axis 5


In [39]:
# Getting first 2 elements from each dimensions
teen[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]]])>

In [40]:
teen[:2,:1,:1,:1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=int32, numpy=
array([[[[1]]],


       [[[1]]]])>

In [41]:
teen[:2,:2,:2,-1]

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])>

In [42]:
tensor_1=tf.constant([[10,7],
                    [7,10]])
tensor_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [43]:
#adding an extra dimension to our rank 2 tensor
tensor_3=tensor_1[...,tf.newaxis]
tensor_3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 7],
        [10]]])>

In [45]:
# alternative to tf.newaxis
tf.expand_dims(tensor_1,axis=-1) # adding an extra dimension at the end

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 7],
        [10]]])>

In [46]:
tf.expand_dims(tensor_1,axis=0) #adding an extra dimension at the 0-dimension

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 7, 10]]])>

In [47]:
tf.expand_dims(tensor_1,axis=1) #adding an extra dimension at the 1-dimension

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 7, 10]]])>

In [50]:
tf.expand_dims(teen,axis=0) #adding an extra dimension at the 0-index dimension

<tf.Tensor: shape=(1, 2, 3, 2, 5), dtype=int32, numpy=
array([[[[[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]],

         [[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]],

         [[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]]],


        [[[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]],

         [[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]],

         [[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]]]]])>

In [51]:
tf.expand_dims(teen,axis=1) #adding an extra dimension at the 1-index dimension

<tf.Tensor: shape=(2, 1, 3, 2, 5), dtype=int32, numpy=
array([[[[[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]],

         [[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]],

         [[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]]]],



       [[[[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]],

         [[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]],

         [[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]]]]])>

Manipulating Tensors


Basic operatoins
'+' '-' '*' '/'

In [52]:
# You can add value to the Tensor using the addition operator
tensor=tf.constant([[10,7],[3,4]])

In [53]:
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [54]:
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [55]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [56]:
tensor/2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

In [57]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [59]:
tf.math.multiply(tensor,5),tf.math.add(tensor,5),tf.math.subtract(tensor,5),tf.math.divide(tensor,5)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[50, 35],
        [15, 20]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[15, 12],
        [ 8,  9]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 5,  2],
        [-2, -1]])>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[2. , 1.4],
        [0.6, 0.8]])>)

* Matrix multiplication in tensorflow

In [60]:
tensor_1=tf.constant([[8,2],[5,7]])

In [62]:
tensor,tensor_1,tf.linalg.matmul(tensor,tensor_1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[8, 2],
        [5, 7]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[115,  69],
        [ 44,  34]])>)

In [63]:
tensor@tensor_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[115,  69],
       [ 44,  34]])>

# Day2

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
  tensor=tf.constant([[10,6],[5,3]])
  tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[130,  78],
       [ 65,  39]])>

In [3]:
x=tf.constant([[3,4],[1,6],[2,9]])

In [4]:
tf.linalg.matmul(tensor,tf.reshape(x,shape=(2,3)))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[66, 52, 64],
       [33, 26, 32]])>

In [6]:
tf.linalg.matmul(tensor,tf.transpose(x))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[54, 46, 74],
       [27, 23, 37]])>

In [7]:
 tensor,x

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  6],
        [ 5,  3]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 4],
        [1, 6],
        [2, 9]])>)

In [9]:
tf.transpose(x),tf.reshape(x,shape=(2,3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 1, 2],
        [4, 6, 9]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 4, 1],
        [6, 2, 9]])>)

In [10]:
#Change the datatype of the tensor
tensor.dtype

tf.int32

In [11]:
x.dtype

tf.int32

In [12]:
#Change the datatype from int32 to int16
x=tf.cast(x,dtype=tf.int16)
x

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[3, 4],
       [1, 6],
       [2, 9]], dtype=int16)>

# Aggregating tensors

 *Aggregating tensors=condensing them from multiple values down to a smaller amount of values

In [13]:
x=tf.constant([-9,-4])
tf.abs(x)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([9, 4])>

* Get the minimum
* Get the maximum
* Get mean of a tensor
* Get the sum of tensor

In [17]:
#Create a random tensor
a=tf.constant(np.random.randint(0,100,size=50))
a

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([78, 50, 85, 35, 66, 72, 60, 21, 67, 86,  6, 16, 29, 64, 82, 51, 99,
       71,  0, 29,  6, 23, 34, 40, 89, 61, 91, 39, 70, 68, 70, 37, 44, 27,
       74, 33,  9,  8, 22, 84, 47, 90, 97, 10, 14, 16, 28, 68, 32, 21])>

In [18]:
tf.size(a),a.shape,a.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [19]:
tf.reduce_min(a)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [20]:
tf.reduce_max(a)

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [21]:
tf.reduce_mean(a)

<tf.Tensor: shape=(), dtype=int32, numpy=48>

In [22]:
tf.reduce_sum(a)

<tf.Tensor: shape=(), dtype=int32, numpy=2419>

In [39]:
tf.math.reduce_variance(tf.cast(a,dtype=float))

<tf.Tensor: shape=(), dtype=float32, numpy=806.4356>

In [40]:
tf.math.reduce_std(tf.cast(a,dtype=float))

<tf.Tensor: shape=(), dtype=float32, numpy=28.39781>

* Finding the positional Maximum and Minimum

In [41]:
#Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
a=tf.random.uniform(shape=[50])
a

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [42]:
#Find the positional maximum
tf.argmax(a)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [43]:
a[tf.argmax(a)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [44]:
tf.reduce_max(a)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [45]:
#check for equality
tf.reduce_max(a)==a[tf.argmax(a)]

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [46]:
tf.reduce_min(a)==a[tf.argmin(a)]

<tf.Tensor: shape=(), dtype=bool, numpy=True>

# Squeezing a tensor(removing all single dimensions)

In [48]:
tf.random.set_seed(42)
a=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
a

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [49]:
a_squeezed=tf.squeeze(a)
a_squeezed,a_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

* ONE HOT ENCODING

In [51]:
#Create a list of indices
some_list=[0,1,2,3,4] # colud be red,blue,green,yellow,black
#one hot encode our list of indices
tf.one_hot(some_list,depth=len(some_list))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [64]:
#Specifying custom values in one-hot encoding
tf.one_hot(some_list,depth=len(some_list),on_value='I Love Mann',off_value='I Hate Preeti')

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'I Love Mann', b'I Hate Preeti', b'I Hate Preeti',
        b'I Hate Preeti', b'I Hate Preeti'],
       [b'I Hate Preeti', b'I Love Mann', b'I Hate Preeti',
        b'I Hate Preeti', b'I Hate Preeti'],
       [b'I Hate Preeti', b'I Hate Preeti', b'I Love Mann',
        b'I Hate Preeti', b'I Hate Preeti'],
       [b'I Hate Preeti', b'I Hate Preeti', b'I Hate Preeti',
        b'I Love Mann', b'I Hate Preeti'],
       [b'I Hate Preeti', b'I Hate Preeti', b'I Hate Preeti',
        b'I Hate Preeti', b'I Love Mann']], dtype=object)>

In [53]:
# squaring,log,square root
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [54]:
# square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [55]:
# Square root
tf.sqrt(tf.cast(H,dtype=float)) #Method require floating value

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [58]:
# log
tf.math.log(tf.cast(H,dtype=float)) #Method does not allow int

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Tensors and Numpy

* Tensorflow interacts beautifully with Numpy arrays

In [59]:
# Creating a tensor from numpy array
a=tf.constant(np.array([3.,7.,10.]))
a

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [60]:
#Convert our tensor back to a numpy array
np.array(a),type(np.array(a))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [61]:
#convert tensor "a" to  a Numpy array
a.numpy(),type(a.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [62]:
a.numpy()[0]

3.0

In [63]:
#the default types of each are slightly different
numpy_j=tf.constant(np.array([3.,7.,10.]))
tensor_j=tf.constant([3.,7.,10.])
#checking the datatypes of each
numpy_j.dtype,tensor_j.dtype

(tf.float64, tf.float32)

In [66]:
tensor=tf.constant(
    [[1,2,3],
    [4,5,6],
    [7,8,9]]
)
tensor.shape

TensorShape([3, 3])

In [69]:
tf.expand_dims(tensor,axis=1)

<tf.Tensor: shape=(3, 1, 3), dtype=int32, numpy=
array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])>